---
abstract: 'Control and read hardware devices with i2c(SMBus)'
author:
  - 'Shantanu Bhadoria <shantanu@cpan.org> L<https://www.shantanubhadoria.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  blib: '1.01'
  perl: '5.010000'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Device-SMBus
no_index:
  directory:
    - corpus
    - examples
    - inc
    - t
    - xt
  package:
    - DB
provides:
  Device::SMBus:
    file: lib/Device/SMBus.pm
    version: '1.15'
  Device::SMBus::Manual:
    file: lib/Device/SMBus/Manual.pm
    version: '1.15'
requires:
  Carp: '0'
  Fcntl: '0'
  IO::File: '0'
  Moo: '0'
  XSLoader: '0'
  constant: '0'
  perl: '5.010000'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/shantanubhadoria/perl-device-smbus/issues
  homepage: https://metacpan.org/release/Device-SMBus
  repository: git://github.com/shantanubhadoria/perl-device-smbus.git
version: '1.15'
x_contributors:
  - 'Joel Maslak <jmaslak@antelope.net>'
  - 'Jonathan Stowe <jns+git@gellyfish.co.uk>'
  - 'Neil Bowers <neil@bowers.com>'
  - 'Shantanu Bhadoria <shantanu att cpan dott org>'
  - 'wfreller <wolfgang@freller.at>'
